server.port=8080
app.cors.origins=http://localhost:63342
tesseract.datapath=C:\\Users\\bbala\\tessdata
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.ge=DEBUG
logging.level.org.springframework.web=INFO

